config/routes.rb
Rails.application.routes.draw do
  resources :yelps

   root 'yelps#index'

end

app/models/yelp.rb
class Yelp < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/yelps_controller.rb
class YelpsController < ApplicationController
  before_action :set_yelp, only: [:show, :edit, :update, :destroy]

  # GET /yelps
  # GET /yelps.json
  def index
    @yelps = Yelp.all
  end

  # GET /yelps/1
  # GET /yelps/1.json
  def show
  end

  # GET /yelps/new
  def new
    @yelp = Yelp.new
  end

  # GET /yelps/1/edit
  def edit
  end

  # POST /yelps
  # POST /yelps.json
  def create
    @yelp = Yelp.new(yelp_params)

    respond_to do |format|
      if @yelp.save
        format.html { redirect_to @yelp, notice: 'Yelp was successfully created.' }
        format.json { render :show, status: :created, location: @yelp }
      else
        format.html { render :new }
        format.json { render json: @yelp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yelps/1
  # PATCH/PUT /yelps/1.json
  def update
    respond_to do |format|
      if @yelp.update(yelp_params)
        format.html { redirect_to @yelp, notice: 'Yelp was successfully updated.' }
        format.json { render :show, status: :ok, location: @yelp }
      else
        format.html { render :edit }
        format.json { render json: @yelp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yelps/1
  # DELETE /yelps/1.json
  def destroy
    @yelp.destroy
    respond_to do |format|
      format.html { redirect_to yelps_url, notice: 'Yelp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yelp
      @yelp = Yelp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yelp_params
      params.require(:yelp).permit(:name, :starts_month_day_year, :starts_time, :ends_month_day_year, :ends_time, :venue_name, :venue_street, :venue_city_state_zip, :event_site_url, :tickets_url, :cost, :description, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/yelps_helper.rb
module YelpsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/yelps/_form.html.erb
<%= form_for(@yelp) do |f| %>
  <% if @yelp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@yelp.errors.count, "error") %> prohibited this yelp from being saved:</h2>

      <ul>
      <% @yelp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :starts_month_day_year %><br>
    <%= f.datetime_select :starts_month_day_year %>
  </div>
  <div class="field">
    <%= f.label :starts_time %><br>
    <%= f.datetime_select :starts_time %>
  </div>
  <div class="field">
    <%= f.label :ends_month_day_year %><br>
    <%= f.datetime_select :ends_month_day_year %>
  </div>
  <div class="field">
    <%= f.label :ends_time %><br>
    <%= f.datetime_select :ends_time %>
  </div>
  <div class="field">
    <%= f.label :venue_name %><br>
    <%= f.text_field :venue_name %>
  </div>
  <div class="field">
    <%= f.label :venue_street %><br>
    <%= f.text_field :venue_street %>
  </div>
  <div class="field">
    <%= f.label :venue_city_state_zip %><br>
    <%= f.text_field :venue_city_state_zip %>
  </div>
  <div class="field">
    <%= f.label :event_site_url %><br>
    <%= f.text_field :event_site_url %>
  </div>
  <div class="field">
    <%= f.label :tickets_url %><br>
    <%= f.text_field :tickets_url %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/yelps/edit.html.erb
<h1>Editing Yelp</h1>

<%= render 'form' %>

<%= link_to 'Show', @yelp %> |
<%= link_to 'Back', yelps_path %>

app/views/yelps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Yelps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Starts month day year</th>
      <th>Starts time</th>
      <th>Ends month day year</th>
      <th>Ends time</th>
      <th>Venue name</th>
      <th>Venue street</th>
      <th>Venue city state zip</th>
      <th>Event site url</th>
      <th>Tickets url</th>
      <th>Cost</th>
      <th>Description</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @yelps.each do |yelp| %>
      <tr>
        <td><%= yelp.name %></td>
        <td><%= yelp.starts_month_day_year %></td>
        <td><%= yelp.starts_time %></td>
        <td><%= yelp.ends_month_day_year %></td>
        <td><%= yelp.ends_time %></td>
        <td><%= yelp.venue_name %></td>
        <td><%= yelp.venue_street %></td>
        <td><%= yelp.venue_city_state_zip %></td>
        <td><%= yelp.event_site_url %></td>
        <td><%= yelp.tickets_url %></td>
        <td><%= yelp.cost %></td>
        <td><%= yelp.description %></td>
        <td><%= yelp.category %></td>
        <td><%= link_to 'Show', yelp %></td>
        <td><%= link_to 'Edit', edit_yelp_path(yelp) %></td>
        <td><%= link_to 'Destroy', yelp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Yelp', new_yelp_path %>

app/views/yelps/new.html.erb
<h1>New Yelp</h1>

<%= render 'form' %>

<%= link_to 'Back', yelps_path %>

app/views/yelps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @yelp.name %>
</p>

<p>
  <strong>Starts month day year:</strong>
  <%= @yelp.starts_month_day_year %>
</p>

<p>
  <strong>Starts time:</strong>
  <%= @yelp.starts_time %>
</p>

<p>
  <strong>Ends month day year:</strong>
  <%= @yelp.ends_month_day_year %>
</p>

<p>
  <strong>Ends time:</strong>
  <%= @yelp.ends_time %>
</p>

<p>
  <strong>Venue name:</strong>
  <%= @yelp.venue_name %>
</p>

<p>
  <strong>Venue street:</strong>
  <%= @yelp.venue_street %>
</p>

<p>
  <strong>Venue city state zip:</strong>
  <%= @yelp.venue_city_state_zip %>
</p>

<p>
  <strong>Event site url:</strong>
  <%= @yelp.event_site_url %>
</p>

<p>
  <strong>Tickets url:</strong>
  <%= @yelp.tickets_url %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @yelp.cost %>
</p>

<p>
  <strong>Description:</strong>
  <%= @yelp.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @yelp.category %>
</p>

<%= link_to 'Edit', edit_yelp_path(@yelp) %> |
<%= link_to 'Back', yelps_path %>